# Why Use NumPy?

#### NumPy aims to provide an array object that is up to 50x faster than traditional Python lists.

# Why is NumPy Faster Than Lists?

#### NumPy arrays are stored at one continuous place in memory unlike lists, so processes can access and manipulate them very efficiently.

In [1]:
import numpy as np

In [2]:
print(np.__version__)

1.21.5


# Create an array

In [3]:
arr1 = np.array(42)
arr1

array(42)

In [4]:
arr1.shape

()

In [12]:
# Get number of diminsions
arr1.ndim

0

In [6]:
arr2 = np.array([1, 2, 3, 4, 5])
arr2

array([1, 2, 3, 4, 5])

In [7]:
arr2.shape

(5,)

In [13]:
# Get number of diminsions
arr2.ndim

1

In [8]:
arr3 = np.array([[1,2,3,4], [5, 6, 7, 8]])
arr3

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [9]:
arr3.shape

(2, 4)

In [15]:
# Get number of diminsions
arr3.ndim

2

In [10]:
arr4 = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])
arr4

array([[[1, 2, 3],
        [4, 5, 6]],

       [[1, 2, 3],
        [4, 5, 6]]])

In [16]:
arr4.shape

(2, 2, 3)

In [17]:
arr4.ndim

3

### Create an array with 5 dimensions and verify that it has 5 dimensions

In [18]:
arr5 = np.array([1, 2, 3, 4], ndmin=5)
arr5

array([[[[[1, 2, 3, 4]]]]])

# Array Indexing

In [20]:
arr2[0]

1

In [22]:
arr3[1]

array([5, 6, 7, 8])

In [23]:
arr3[1,2]

7

In [25]:
arr5[0,0,0,0]

array([1, 2, 3, 4])

In [26]:
arr5[0,0,0,0,0]

1

In [29]:
arr5[0,0,0,0,0].shape

()

In [30]:
arr5[0,0,0,0,0].ndim

0

In [27]:
arr5[0,0,0,0].shape

(4,)

In [28]:
arr5[0,0,0,0].ndim

1

# Array Slicing

In [35]:
arr2[1:3]

array([2, 3])

In [36]:
arr2[1:]

array([2, 3, 4, 5])

In [38]:
arr3[1:]

array([[5, 6, 7, 8]])

In [39]:
arr3[:1]

array([[1, 2, 3, 4]])

In [40]:
arr2[-3:-1]

array([3, 4])

In [41]:
arr6 = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11])
arr6

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [42]:
arr6[-2:-5]

array([], dtype=int32)

In [43]:
arr6[-5:-2]

array([7, 8, 9])

In [44]:
arr6[-5:]

array([ 7,  8,  9, 10, 11])

In [45]:
arr7 = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
arr7

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [46]:
arr7[0:2, 1:4]

array([[2, 3, 4],
       [7, 8, 9]])

# Data Types

In [47]:
arr7.dtype

dtype('int32')

In [48]:
arr8 = np.array(['apple', 'banana', 'cherry'])
arr8

array(['apple', 'banana', 'cherry'], dtype='<U6')

In [49]:
arr9 = np.array([1, 2, 3, 4], dtype='S')
arr9

array([b'1', b'2', b'3', b'4'], dtype='|S1')

In [50]:
arr9[1]

b'2'

In [51]:
str(arr9[1])

"b'2'"

# Array Copy vs View

### The copy is a new array, and the view is just a view of the original array.

In [63]:
arr10 = np.array([1, 2, 3, 4, 5])

x = arr10.copy()
y = arr10.view()

print(x.base)
print(y.base)

None
[1 2 3 4 5]


In [58]:
y[0] = 10
y

array([10,  2,  3,  4,  5])

In [64]:
arr10

array([1, 2, 3, 4, 5])

In [60]:
x

array([1, 2, 3, 4, 5])

In [61]:
x[3]= 20
x

array([ 1,  2,  3, 20,  5])

In [65]:
arr10

array([1, 2, 3, 4, 5])

In [70]:
arr11 = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11,12])
arr11

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [71]:
newarr = arr11.reshape(4, 3)
newarr

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [73]:
newarr2 = arr11.reshape(2, 3, 2)
newarr2

array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6]],

       [[ 7,  8],
        [ 9, 10],
        [11, 12]]])

# Flattening the arrays

In [74]:
arr3

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [75]:
arr3.reshape(-1)

array([1, 2, 3, 4, 5, 6, 7, 8])

In [78]:
arr3

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [76]:
arr5

array([[[[[1, 2, 3, 4]]]]])

In [77]:
arr5.reshape(-1)

array([1, 2, 3, 4])

In [79]:
arr5

array([[[[[1, 2, 3, 4]]]]])

# Array Iterating

In [80]:
arr4

array([[[1, 2, 3],
        [4, 5, 6]],

       [[1, 2, 3],
        [4, 5, 6]]])

In [81]:
arr4.shape

(2, 2, 3)

In [85]:
import time

In [86]:
t0 = time.time()
for x in arr4:
    for y in x:
        for z in y:
            print(z)
t1 = time.time()
print(t1 - t0)

1
2
3
4
5
6
1
2
3
4
5
6
0.0010123252868652344


In [88]:
t0 = time.time()
flattenArr4 = arr4.reshape(-1)
for i in flattenArr4:
    print(i)
t1 = time.time()
print(t1 - t0)

1
2
3
4
5
6
1
2
3
4
5
6
0.0009658336639404297


## Iterating Arrays Using nditer()

In [91]:
arr4

array([[[1, 2, 3],
        [4, 5, 6]],

       [[1, 2, 3],
        [4, 5, 6]]])

In [92]:
arr4.shape

(2, 2, 3)

In [89]:
t0 = time.time()
for x in np.nditer(arr4):
    print(x)
t1 = time.time()
print(t1 - t0)

1
2
3
4
5
6
1
2
3
4
5
6
0.0009968280792236328


In [93]:
for x in np.nditer(arr4[:, :, ::2]):
    print(x)

1
3
4
6
1
3
4
6


## Enumerated Iteration Using ndenumerate()

### Get numer with its index

In [96]:
arr12 = np.array([1, 2, 3])

for idx, x in np.ndenumerate(arr12):
    print(idx, x)

(0,) 1
(1,) 2
(2,) 3


In [97]:
np.ndenumerate(arr12)

In [98]:
list(np.ndenumerate(arr12))

[((0,), 1), ((1,), 2), ((2,), 3)]

# Joining Arrays

In [99]:
arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr1_2 = np.concatenate((arr1, arr2))
arr1_2

array([1, 2, 3, 4, 5, 6])

In [109]:
arr1 = np.array([[1, 2], [3, 4]])

arr2 = np.array([[5, 6], [7, 8]])

arr1_2 = np.concatenate((arr1, arr2), axis=0)
arr1_2

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [110]:
arr1_2.shape

(4, 2)

In [111]:
arr1 = np.array([[1, 2], [3, 4]])

arr2 = np.array([[5, 6], [7, 8]])

arr1_2 = np.concatenate((arr1, arr2), axis=1)
arr1_2

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

In [112]:
arr1_2.shape

(2, 4)

## Stacking Along Rows

In [113]:
import numpy as np

arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr1_2 = np.hstack((arr1, arr2))
arr1_2

array([1, 2, 3, 4, 5, 6])

In [115]:
arr1 = np.array([[1, 2], [3, 4]])

arr2 = np.array([[5, 6], [7, 8]])

arr1_2 = np.hstack((arr1, arr2))
arr1_2

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

## Stacking Along Columns

In [116]:
arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr1_2 = np.vstack((arr1, arr2))
arr1_2

array([[1, 2, 3],
       [4, 5, 6]])

In [117]:
arr1 = np.array([[1, 2], [3, 4]])

arr2 = np.array([[5, 6], [7, 8]])

arr1_2 = np.vstack((arr1, arr2))
arr1_2

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

## Stacking Along Height (depth)

In [118]:
arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr1_2 = np.dstack((arr1, arr2))
arr1_2

array([[[1, 4],
        [2, 5],
        [3, 6]]])

In [119]:
arr1 = np.array([[1, 2], [3, 4]])

arr2 = np.array([[5, 6], [7, 8]])

arr1_2 = np.dstack((arr1, arr2))
arr1_2

array([[[1, 5],
        [2, 6]],

       [[3, 7],
        [4, 8]]])

## Splitting Array

In [121]:
arr = np.array([1, 2, 3, 4, 5, 6])
split_arr = np.array_split(arr, 3)
split_arr

[array([1, 2]), array([3, 4]), array([5, 6])]

In [122]:
arr = np.array([1, 2, 3, 4, 5, 6])
split_arr = np.array_split(arr, 5)
split_arr

[array([1, 2]), array([3]), array([4]), array([5]), array([6])]

In [125]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]])

split_arr = np.array_split(arr, 3)
split_arr

[array([[1, 2, 3],
        [4, 5, 6]]),
 array([[ 7,  8,  9],
        [10, 11, 12]]),
 array([[13, 14, 15],
        [16, 17, 18]])]

In [127]:
split_arr = np.array_split(arr, 6)
split_arr

[array([[1, 2, 3]]),
 array([[4, 5, 6]]),
 array([[7, 8, 9]]),
 array([[10, 11, 12]]),
 array([[13, 14, 15]]),
 array([[16, 17, 18]])]

In [131]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]])

split_arr = np.array_split(arr, 3, axis=1)
split_arr

[array([[ 1],
        [ 4],
        [ 7],
        [10],
        [13],
        [16]]),
 array([[ 2],
        [ 5],
        [ 8],
        [11],
        [14],
        [17]]),
 array([[ 3],
        [ 6],
        [ 9],
        [12],
        [15],
        [18]])]

# Searching Arrays

In [132]:
arr = np.array([1, 2, 3, 4, 5, 4, 4])

i = np.where(arr == 4)
i

(array([3, 5, 6], dtype=int64),)

In [133]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

i = np.where(arr%2 == 0)
i

(array([1, 3, 5, 7], dtype=int64),)

In [134]:
arr = np.array([6, 7, 8, 9])

i = np.searchsorted(arr, 7)

i

1

In [135]:
arr = np.array([6, 7, 8, 9])
i = np.searchsorted(arr, 7, side='right')
i

2

### Multiple Values

In [136]:
arr = np.array([1, 3, 5, 7])
indices = np.searchsorted(arr, [2, 4, 6])
indices

array([1, 2, 3], dtype=int64)

# Sorting Arrays

In [137]:
arr = np.array([3, 2, 0, 1])
np.sort(arr)

array([0, 1, 2, 3])

In [138]:
arr

array([3, 2, 0, 1])

In [139]:
arr = np.array(['banana', 'cherry', 'apple'])
np.sort(arr)

array(['apple', 'banana', 'cherry'], dtype='<U6')

In [140]:
arr = np.array([True, False, True])
np.sort(arr)

array([False,  True,  True])

In [141]:
arr = np.array([[3, 2, 4], [5, 0, 1]])
np.sort(arr)

array([[2, 3, 4],
       [0, 1, 5]])

# Filtering Arrays

In [142]:
arr = np.array([41, 42, 43, 44])

x = [True, False, True, False]

filtered_arr = arr[x]
filtered_arr

array([41, 43])

In [144]:
arr[arr>42]

array([43, 44])