In [1]:
import numpy as np

# Generate Random Number

In [2]:
x = np.random.randint(100) # x will be in range [0,99]
x

47

# Generate Random Float

In [3]:
x = np.random.rand() # x will be in range [0, 1]
x

0.7500898300729661

# Generate Random Array

In [4]:
# Generate a 1-D array containing 5 random integers from 0 to 99:
x = np.random.randint(100, size=(5))
x

array([12, 56, 15,  5,  3])

In [5]:
# Generate a 2-D array with 3 rows, each row containing 5 random integers from 0 to 99:
x = np.random.randint(100, size=(3, 5))
x

array([[74, 87, 25, 45, 71],
       [71, 19, 92, 93,  6],
       [45, 93, 46, 56, 22]])

In [6]:
# Generate a 1-D array containing 5 random floats:
x = np.random.rand(5)
x

array([0.4016084 , 0.5328188 , 0.18536105, 0.32192419, 0.46903477])

In [7]:
# Generate a 2-D array with 3 rows, each row containing 5 random numbers:
x = np.random.rand(3,5)
x

array([[0.56402516, 0.63720116, 0.57083402, 0.84988627, 0.49924771],
       [0.18050362, 0.03631698, 0.04043709, 0.54194911, 0.57957712],
       [0.4813553 , 0.35665601, 0.4980819 , 0.95572478, 0.39235985]])

# Generate Random Number From Array

In [8]:
# randomly returns one of the values.
x = np.random.choice([3, 5, 7, 9])
x

5

In [9]:
# Generate a 2-D array that consists of the values in the array parameter (3, 5, 7, and 9):
x = np.random.choice([3, 5, 7, 9], size=(3, 5))
x

array([[3, 3, 7, 5, 5],
       [7, 5, 7, 9, 3],
       [7, 9, 9, 5, 7]])

# Random Data Distribution

## A random distribution is a set of random numbers that follow a certain probability density function.

## Example
#### Generate a 1-D array containing 100 values, where each value has to be 3, 5, 7 or 9.

#### The probability for the value to be 3 is set to be 0.1

#### The probability for the value to be 5 is set to be 0.3

#### The probability for the value to be 7 is set to be 0.6

#### The probability for the value to be 9 is set to be 0

In [10]:
x = np.random.choice([3, 5, 7, 9], p=[0.1, 0.3, 0.6, 0.0], size=(100))
x

array([7, 7, 5, 5, 7, 5, 7, 5, 7, 3, 5, 3, 7, 7, 5, 7, 7, 7, 7, 5, 5, 5,
       7, 7, 7, 7, 7, 7, 3, 7, 7, 7, 7, 7, 7, 7, 3, 5, 5, 7, 7, 7, 7, 5,
       7, 7, 7, 3, 5, 7, 5, 7, 3, 7, 7, 7, 7, 7, 5, 7, 7, 3, 7, 7, 7, 7,
       5, 5, 5, 3, 7, 7, 7, 7, 3, 7, 7, 7, 7, 7, 7, 7, 5, 7, 7, 7, 5, 7,
       7, 7, 5, 7, 7, 5, 7, 7, 5, 7, 5, 7])

In [11]:
y = list(x)
y.count(7)/100

0.67

In [12]:
y.count(3)/100

0.09

In [13]:
y.count(5)/100

0.24

In [14]:
y.count(9)/100

0.0

In [15]:
x = np.random.choice([3, 5, 7, 9], p=[0.1, 0.3, 0.6, 0.0], size=(3, 5))
x

array([[7, 7, 7, 7, 5],
       [7, 7, 7, 7, 7],
       [3, 3, 5, 3, 7]])

In [16]:
y.count(7)/(3*5)

4.466666666666667

# Random Permutations of Elements

In [17]:
# changing arrangement of elements in-place. i.e. in the array itself.
arr = np.array([1, 2, 3, 4, 5])

np.random.shuffle(arr)

In [18]:
arr

array([4, 5, 3, 1, 2])

## Generating Permutation of Arrays

In [19]:
arr = np.array([1, 2, 3, 4, 5])
np.random.permutation(arr)

array([4, 1, 5, 2, 3])