# add()

In [1]:
import numpy as np

x = [1, 2, 3, 4]
y = [4, 5, 6, 7]
z = np.add(x, y)

print(z)

[ 5  7  9 11]


In [2]:
arr1 = np.array([10, 11, 12, 13, 14, 15])
arr2 = np.array([20, 21, 22, 23, 24, 25])

newarr = np.add(arr1, arr2)

print(newarr)

[30 32 34 36 38 40]


## subtract()

In [3]:
arr1 = np.array([10, 20, 30, 40, 50, 60])
arr2 = np.array([20, 21, 22, 23, 24, 25])

newarr = np.subtract(arr1, arr2)

print(newarr)

[-10  -1   8  17  26  35]


## multiply()

In [4]:
arr1 = np.array([10, 20, 30, 40, 50, 60])
arr2 = np.array([20, 21, 22, 23, 24, 25])

newarr = np.multiply(arr1, arr2)

print(newarr)

[ 200  420  660  920 1200 1500]


## divide()

In [5]:
arr1 = np.array([10, 20, 30, 40, 50, 60])
arr2 = np.array([3, 5, 10, 8, 2, 33])

newarr = np.divide(arr1, arr2)

print(newarr)

[ 3.33333333  4.          3.          5.         25.          1.81818182]


In [6]:
newarr.astype(int)

array([ 3,  4,  3,  5, 25,  1])

In [7]:
np.floor_divide(arr1, arr2)

array([ 3,  4,  3,  5, 25,  1], dtype=int32)

## power()

In [8]:
arr1 = np.array([10, 20, 30, 40, 50, 60])
arr2 = np.array([3, 5, 6, 8, 2, 33])

newarr = np.power(arr1, arr2)

print(newarr)

[      1000    3200000  729000000 -520093696       2500          0]


## mod

In [9]:
arr1 = np.array([10, 20, 30, 40, 50, 60])
arr2 = np.array([3, 7, 9, 8, 2, 33])

newarr = np.mod(arr1, arr2)

print(newarr)

[ 1  6  3  0  0 27]


## remainder()

In [10]:
import numpy as np

arr1 = np.array([10, 20, 30, 40, 50, 60])
arr2 = np.array([3, 7, 9, 8, 2, 33])

newarr = np.remainder(arr1, arr2)

print(newarr)

[ 1  6  3  0  0 27]


## divmod

In [11]:
arr1 = np.array([10, 20, 30, 40, 50, 60])
arr2 = np.array([3, 7, 9, 8, 2, 33])

newarr = np.divmod(arr1, arr2)

print(newarr)

(array([ 3,  2,  3,  5, 25,  1], dtype=int32), array([ 1,  6,  3,  0,  0, 27], dtype=int32))


## absolute()

In [12]:
arr = np.array([-1, -2, 1, 2, 3, -4])

newarr = np.absolute(arr)

print(newarr)

[1 2 1 2 3 4]


# sum()

In [13]:
arr = np.array([[2, 4], [5, 6]])
arr

array([[2, 4],
       [5, 6]])

In [14]:
np.sum(arr)

17

In [15]:
np.sum(arr, axis = 0) # sum columns

array([ 7, 10])

In [16]:
np.sum(arr, axis = 1) # sum rows

array([ 6, 11])

# prod()

In [17]:
np.prod(arr)

240

In [18]:
np.prod(arr, axis = 0)

array([10, 24])

In [19]:
np.prod(arr, axis = 1)

array([ 8, 30])

# matmul()

In [20]:
arr1 = np.array([[1, 2],[3, 4]])
arr2 = arr1.copy()
np.matmul(arr1, arr2)

array([[ 7, 10],
       [15, 22]])

# inner()

In [21]:
np.inner(arr1, arr2)

array([[ 5, 11],
       [11, 25]])

# outer()

In [22]:
np.outer(arr1, arr2)

array([[ 1,  2,  3,  4],
       [ 2,  4,  6,  8],
       [ 3,  6,  9, 12],
       [ 4,  8, 12, 16]])