# Linear Algebra

In [1]:
import numpy as np

In [2]:
arr1 = np.array([[6, 1, 1],
              [4, -2, 5],
              [2, 8, 7]])
arr1

array([[ 6,  1,  1],
       [ 4, -2,  5],
       [ 2,  8,  7]])

# matrix_rank

In [3]:
# Rank of a matrix
np.linalg.matrix_rank(arr1)

3

In [4]:
arr2 = np.array([[3, -4, 8], [0, -1, 5], [0, 0, -1]])
arr2

array([[ 3, -4,  8],
       [ 0, -1,  5],
       [ 0,  0, -1]])

In [5]:
np.linalg.matrix_rank(arr2)

3

In [6]:
arr3 = np.array([[0, 1, 3, -1], [2, 0, 0, 0], [2, 7, 4, 0]])
arr3

array([[ 0,  1,  3, -1],
       [ 2,  0,  0,  0],
       [ 2,  7,  4,  0]])

In [7]:
np.linalg.matrix_rank(arr3)

3

In [8]:
arr4 = np.eye(4)
arr4

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [9]:
np.linalg.matrix_rank(arr4)

4

# trace
### Return the sum along diagonals of the array.

In [10]:
np.trace(arr1)

11

In [11]:
np.trace(arr2)

1

In [12]:
np.trace(arr3)

4

In [13]:
np.trace(arr4)

4.0

# det
### Compute the determinant of an array.

In [14]:
np.linalg.det(arr1)

-306.0

In [15]:
np.linalg.det(arr2)

3.0000000000000004

In [16]:
np.linalg.det(arr4)

1.0

In [17]:
arr5 = np.array([[1, 5],[7, 40]])
arr5

array([[ 1,  5],
       [ 7, 40]])

In [18]:
np.linalg.det(arr5)

4.999999999999997

In [19]:
np.round(np.linalg.det(arr5))

5.0

# inv
### Compute the (multiplicative) inverse of a matrix.

In [20]:
np.linalg.inv(arr5)

array([[ 8. , -1. ],
       [-1.4,  0.2]])

# matrix_power
### Raise a square matrix to the (integer) power n.

In [21]:
np.linalg.matrix_power(arr5, 2)

array([[  36,  205],
       [ 287, 1635]])

In [22]:
arr6 = np.array([[1, 2], [3, 4]])
arr6

array([[1, 2],
       [3, 4]])

In [23]:
np.linalg.matrix_power(arr6, 2)

array([[ 7, 10],
       [15, 22]])

In [24]:
np.matmul(arr5, arr5)

array([[  36,  205],
       [ 287, 1635]])